#pragma once

#include "LogLevel.h"
#include <string>
#include <chrono>
#include <unordered_map>

#define OTEL_PHP_BOOTSTRAP_PHP_PART_FILE bootstrap_php_part_file
#define OTEL_PHP_ENABLED enabled

#define OTEL_PHP_LOG_FILE log_file
#define OTEL_PHP_LOG_LEVEL log_level
#define OTEL_PHP_LOG_LEVEL_FILE log_level_file
#define OTEL_PHP_LOG_LEVEL_STDERR log_level_stderr
#define OTEL_PHP_LOG_LEVEL_SYSLOG log_level_syslog
#define OTEL_PHP_LOG_FEATURES log_features
#define OTEL_PHP_DEBUG_DIAGNOSTICS_FILE debug_diagnostic_file
#define OTEL_PHP_MAX_SEND_QUEUE_SIZE max_send_queue_size
#define OTEL_PHP_ASYNC_TRANSPORT async_transport
#define OTEL_PHP_ASYNC_TRANSPORT_SHUTDOWN_TIMEOUT async_transport_shutdown_timeout

#define OTEL_PHP_DEBUG_INSTRUMENT_ALL debug_instrument_all
#define OTEL_PHP_DEBUG_PHP_HOOKS_ENABLED debug_php_hooks_enabled
#define OTEL_PHP_ATTR_HOOKS_ENABLED attr_hooks_enabled
#define OTEL_PHP_SCOPED_DEPS_ENABLED scoped_deps_enabled

#define OTEL_PHP_INFERRED_SPANS_ENABLED inferred_spans_enabled
#define OTEL_PHP_INFERRED_SPANS_REDUCTION_ENABLED inferred_spans_reduction_enabled
#define OTEL_PHP_INFERRED_SPANS_STACKTRACE_ENABLED inferred_spans_stacktrace_enabled
#define OTEL_PHP_INFERRED_SPANS_SAMPLING_INTERVAL inferred_spans_sampling_interval
#define OTEL_PHP_INFERRED_SPANS_MIN_DURATION inferred_spans_min_duration

#define OTEL_PHP_DEPENDENCY_AUTOLOADER_GUARD_ENABLED dependency_autoloader_guard_enabled

// This ooption is used by PHP part
#define OTEL_PHP_USER_BOOTSTRAP_PHP_FILE user_bootstrap_php_file

#define OTEL_PHP_OPENTELEMETRY_EXTENSION_EMULATION_ENABLED opentelemetry_extension_emulation_enabled

#define OTEL_PHP_NATIVE_OTLP_SERIALIZER_ENABLED native_otlp_serializer_enabled

#define OTEL_PHP_OPAMP_HEADERS opamp_headers
#define OTEL_PHP_OPAMP_ENDPOINT opamp_endpoint

#define OTEL_PHP_OPAMP_HEARTBEAT_INTERVAL opamp_heartbeat_interval
#define OTEL_PHP_OPAMP_POLLING_INTERVAL opamp_polling_interval
#define OTEL_PHP_OPAMP_SEND_TIMEOUT opamp_send_timeout
#define OTEL_PHP_OPAMP_SEND_MAX_RETRIES opamp_send_max_retries
#define OTEL_PHP_OPAMP_SEND_RETRY_DELAY opamp_send_retry_delay

#define OTEL_PHP_OPAMP_INSECURE opamp_insecure
#define OTEL_PHP_OPAMP_CERTIFICATE opamp_certificate
#define OTEL_PHP_OPAMP_CLIENT_CERTIFICATE opamp_client_certificate
#define OTEL_PHP_OPAMP_CLIENT_KEY opamp_client_key
#define OTEL_PHP_OPAMP_CLIENT_KEYPASS opamp_client_keypass

#define OTEL_EXPORTER_OTLP_INSECURE OTEL_EXPORTER_OTLP_INSECURE
#define OTEL_EXPORTER_OTLP_CERTIFICATE OTEL_EXPORTER_OTLP_CERTIFICATE
#define OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
#define OTEL_EXPORTER_OTLP_CLIENT_KEY OTEL_EXPORTER_OTLP_CLIENT_KEY
#define OTEL_EXPORTER_OTLP_CLIENT_KEYPASS OTEL_EXPORTER_OTLP_CLIENT_KEYPASS

#define OTEL_EXPORTER_OTLP_TRACES_INSECURE OTEL_EXPORTER_OTLP_TRACES_INSECURE
#define OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE
#define OTEL_EXPORTER_OTLP_TRACES_CLIENT_CERTIFICATE OTEL_EXPORTER_OTLP_TRACES_CLIENT_CERTIFICATE
#define OTEL_EXPORTER_OTLP_TRACES_CLIENT_KEY OTEL_EXPORTER_OTLP_TRACES_CLIENT_KEY
#define OTEL_EXPORTER_OTLP_TRACES_CLIENT_KEYPASS OTEL_EXPORTER_OTLP_TRACES_CLIENT_KEYPASS

#define OTEL_EXPORTER_OTLP_METRICS_INSECURE OTEL_EXPORTER_OTLP_METRICS_INSECURE
#define OTEL_EXPORTER_OTLP_METRICS_CERTIFICATE OTEL_EXPORTER_OTLP_METRICS_CERTIFICATE
#define OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE
#define OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY
#define OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEYPASS OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEYPASS

#define OTEL_EXPORTER_OTLP_LOGS_INSECURE OTEL_EXPORTER_OTLP_LOGS_INSECURE
#define OTEL_EXPORTER_OTLP_LOGS_CERTIFICATE OTEL_EXPORTER_OTLP_LOGS_CERTIFICATE
#define OTEL_EXPORTER_OTLP_LOGS_CLIENT_CERTIFICATE OTEL_EXPORTER_OTLP_LOGS_CLIENT_CERTIFICATE
#define OTEL_EXPORTER_OTLP_LOGS_CLIENT_KEY OTEL_EXPORTER_OTLP_LOGS_CLIENT_KEY
#define OTEL_EXPORTER_OTLP_LOGS_CLIENT_KEYPASS OTEL_EXPORTER_OTLP_LOGS_CLIENT_KEYPASS

#define OTEL_EXPORTER_OTLP_ENDPOINT OTEL_EXPORTER_OTLP_ENDPOINT
#define OTEL_EXPORTER_OTLP_TRACES_ENDPOINT OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
#define OTEL_EXPORTER_OTLP_METRICS_ENDPOINT OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
#define OTEL_EXPORTER_OTLP_LOGS_ENDPOINT OTEL_EXPORTER_OTLP_LOGS_ENDPOINT

namespace opentelemetry::php {

using namespace std::string_literals;
using namespace std::chrono_literals;

struct ConfigurationSnapshot {
    using configFiles_t = std::unordered_map<std::string, std::string>; // filename->content

    std::string OTEL_PHP_BOOTSTRAP_PHP_PART_FILE;
    bool OTEL_PHP_ENABLED = true;
    std::string OTEL_PHP_LOG_FILE;
    LogLevel OTEL_PHP_LOG_LEVEL = LogLevel::logLevel_off;
    LogLevel OTEL_PHP_LOG_LEVEL_FILE = LogLevel::logLevel_off;
    LogLevel OTEL_PHP_LOG_LEVEL_STDERR = LogLevel::logLevel_off;
    LogLevel OTEL_PHP_LOG_LEVEL_SYSLOG = LogLevel::logLevel_info;
    std::string OTEL_PHP_LOG_FEATURES;
    std::string OTEL_PHP_DEBUG_DIAGNOSTICS_FILE;
    std::size_t OTEL_PHP_MAX_SEND_QUEUE_SIZE = 2 * 1024 * 1204;
    bool OTEL_PHP_ASYNC_TRANSPORT = true;
    std::chrono::milliseconds OTEL_PHP_ASYNC_TRANSPORT_SHUTDOWN_TIMEOUT = std::chrono::seconds(30);
    bool OTEL_PHP_DEBUG_INSTRUMENT_ALL = false;
    bool OTEL_PHP_DEBUG_PHP_HOOKS_ENABLED = false;
    bool OTEL_PHP_ATTR_HOOKS_ENABLED = false;
    bool OTEL_PHP_SCOPED_DEPS_ENABLED = true;

    bool OTEL_PHP_INFERRED_SPANS_ENABLED = false;
    bool OTEL_PHP_INFERRED_SPANS_REDUCTION_ENABLED = true;
    bool OTEL_PHP_INFERRED_SPANS_STACKTRACE_ENABLED = true;
    std::chrono::milliseconds OTEL_PHP_INFERRED_SPANS_SAMPLING_INTERVAL = std::chrono::milliseconds(50);
    std::chrono::milliseconds OTEL_PHP_INFERRED_SPANS_MIN_DURATION = std::chrono::milliseconds(0);

    bool OTEL_PHP_DEPENDENCY_AUTOLOADER_GUARD_ENABLED = false;
    bool OTEL_PHP_OPENTELEMETRY_EXTENSION_EMULATION_ENABLED = true;
    bool OTEL_PHP_NATIVE_OTLP_SERIALIZER_ENABLED = true;
    std::string OTEL_PHP_USER_BOOTSTRAP_PHP_FILE;

    std::string OTEL_PHP_OPAMP_HEADERS;
    std::string OTEL_PHP_OPAMP_ENDPOINT;
    std::chrono::milliseconds OTEL_PHP_OPAMP_HEARTBEAT_INTERVAL = 30s;
    std::chrono::milliseconds OTEL_PHP_OPAMP_POLLING_INTERVAL = 30s;
    std::chrono::milliseconds OTEL_PHP_OPAMP_SEND_TIMEOUT = 10s;
    std::size_t OTEL_PHP_OPAMP_SEND_MAX_RETRIES = 3;
    std::chrono::milliseconds OTEL_PHP_OPAMP_SEND_RETRY_DELAY = 10s;

    bool OTEL_PHP_OPAMP_INSECURE = false;
    std::string OTEL_PHP_OPAMP_CERTIFICATE;
    std::string OTEL_PHP_OPAMP_CLIENT_CERTIFICATE;
    std::string OTEL_PHP_OPAMP_CLIENT_KEYPASS;
    std::string OTEL_PHP_OPAMP_CLIENT_KEY;

    bool OTEL_EXPORTER_OTLP_INSECURE = false;
    std::string OTEL_EXPORTER_OTLP_CERTIFICATE;
    std::string OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE;
    std::string OTEL_EXPORTER_OTLP_CLIENT_KEY;
    std::string OTEL_EXPORTER_OTLP_CLIENT_KEYPASS;

    bool OTEL_EXPORTER_OTLP_TRACES_INSECURE = false;
    std::string OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE;
    std::string OTEL_EXPORTER_OTLP_TRACES_CLIENT_CERTIFICATE;
    std::string OTEL_EXPORTER_OTLP_TRACES_CLIENT_KEY;
    std::string OTEL_EXPORTER_OTLP_TRACES_CLIENT_KEYPASS;

    bool OTEL_EXPORTER_OTLP_METRICS_INSECURE = false;
    std::string OTEL_EXPORTER_OTLP_METRICS_CERTIFICATE;
    std::string OTEL_EXPORTER_OTLP_METRICS_CLIENT_CERTIFICATE;
    std::string OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEY;
    std::string OTEL_EXPORTER_OTLP_METRICS_CLIENT_KEYPASS;

    bool OTEL_EXPORTER_OTLP_LOGS_INSECURE = false;
    std::string OTEL_EXPORTER_OTLP_LOGS_CERTIFICATE;
    std::string OTEL_EXPORTER_OTLP_LOGS_CLIENT_CERTIFICATE;
    std::string OTEL_EXPORTER_OTLP_LOGS_CLIENT_KEY;
    std::string OTEL_EXPORTER_OTLP_LOGS_CLIENT_KEYPASS;

    std::string OTEL_EXPORTER_OTLP_ENDPOINT;
    std::string OTEL_EXPORTER_OTLP_TRACES_ENDPOINT;
    std::string OTEL_EXPORTER_OTLP_METRICS_ENDPOINT;
    std::string OTEL_EXPORTER_OTLP_LOGS_ENDPOINT;

    uint64_t revision = 0;
    configFiles_t remoteConfigFiles;
};

} // namespace opentelemetry::php
