FROM centos:8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177 as devtools

ARG USER_NAME=build

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|# baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y update  && yum -y install sudo curl wget git make autoconf bzip2 zlib-devel bison \
python3 python3-pip  \
util-linux passwd \
gcc binutils gcc-c++

RUN adduser -p password ${USER_NAME} \
&& passwd -d ${USER_NAME} \
&& echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers

USER ${USER_NAME}

RUN mkdir -p /home/${USER_NAME}/prerequisities
WORKDIR /home/${USER_NAME}/prerequisities

ARG GCC_VERSION

RUN curl -LO https://gcc.gnu.org/pub/gcc/releases/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.xz \
&& tar -xf gcc-${GCC_VERSION}.tar.xz \
&& rm gcc-${GCC_VERSION}.tar.xz

RUN cd gcc-${GCC_VERSION} \
&& ./contrib/download_prerequisites \
&& CFG_OPTIONS="--enable-languages=c,c++ --enable-shared --enable-linker-build-id --with-system-zlib --without-included-gettext --enable-threads=posix --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --disable-werror --enable-checking=release --with-pic --disable-symvers --enable-obsolete \
--disable-libstdcxx-visibility --with-tune=generic --enable-libstdcxx-debug-flags=-gdwarf-2 --disable-multilib \
--build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu" \
&& echo $CFG_OPTIONS \
&& ./configure --prefix=/opt/gcc-${GCC_VERSION} $CFG_OPTIONS \
&& make -j$(nproc) \
&& sudo make install \
&& cd - \
&& rm -rf gcc-${GCC_VERSION}

ARG BINUTILS_VERSION

RUN curl -LO https://ftp.gnu.org/gnu/binutils/binutils-${BINUTILS_VERSION}.tar.xz \
&& tar -xf binutils-${BINUTILS_VERSION}.tar.xz \
&& rm binutils-${BINUTILS_VERSION}.tar.xz

RUN cd binutils-${BINUTILS_VERSION} \
&& ./configure --prefix=/opt/binutils-${BINUTILS_VERSION} CFLAGS=-Wno-unused-value --enable-gold \
&& make -j$(nproc) \
&& sudo make install \
&& cd - \
&& rm -rf binutils-${BINUTILS_VERSION}

ARG CMAKE_VERSION

RUN curl -OL https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh \
&& chmod +x cmake-${CMAKE_VERSION}-linux-x86_64.sh \
&& sudo mkdir -p /opt/cmake-${CMAKE_VERSION} \
&& sudo ./cmake-${CMAKE_VERSION}-linux-x86_64.sh --skip-license --prefix=/opt/cmake-${CMAKE_VERSION} \
&& rm cmake-${CMAKE_VERSION}-linux-x86_64.sh

ARG PYTHON_VERSION

RUN curl -LO https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz \
&& tar -xf Python-${PYTHON_VERSION}.tgz \
&& rm Python-${PYTHON_VERSION}.tgz

RUN sudo yum -y install libffi-devel openssl-devel sqlite-devel readline-devel xz-devel bzip2-devel

RUN cd Python-${PYTHON_VERSION} \
 && ./configure --help \
 && ./configure --enable-optimizations --prefix=/opt/python-${PYTHON_VERSION} \
 && make \
 && sudo make install

RUN sudo yum -y clean all

FROM centos:8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177

ARG USER_NAME=build

COPY --from=devtools /opt /opt

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|# baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y update && yum -y install sudo curl wget git make autoconf bzip2 passwd \
    perl-Thread-Queue perl-IPC-Cmd perl-Digest-SHA perl-Time-Piece \
    file \
    glibc-devel \
    && sudo yum -y clean all

RUN adduser -p password ${USER_NAME} \
    && passwd -d ${USER_NAME} \
    && echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers


ARG GCC_VERSION
ARG BINUTILS_VERSION
ARG CMAKE_VERSION
ARG PYTHON_VERSION

RUN set -eux; \
    ln -sf "/opt/binutils-${BINUTILS_VERSION}" /opt/php-distro-build-binutils; \
    ln -sf "/opt/cmake-${CMAKE_VERSION}"       /opt/php-distro-build-cmake; \
    ln -sf "/opt/python-${PYTHON_VERSION}"     /opt/php-distro-build-python;  \
    ln -sf "/opt/gcc-${GCC_VERSION}"               /opt/php-distro-build-gcc

USER ${USER_NAME}

ENV PATH="/opt/php-distro-build-binutils/bin:/opt/php-distro-build-cmake/bin:/opt/php-distro-build-python/bin:/opt/php-distro-build-gcc/bin:${PATH}"

ENV CMAKE_INSTALL_PREFIX=/opt/php-distro-build-cmake

RUN cmake --version \
    && python3 --version \
    && ld --version | head -n 1 \
    &&  gcc --version | head -n 1 \
    && ldd --version
