ARG ALPINE_VERSION=3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
FROM alpine:${ALPINE_VERSION} as devtools_alpine

ARG USER_NAME=build

#binutils: bison - gprofng, texinfo - makeinfo

RUN apk update \
    && apk add sudo curl wget git make autoconf bzip2 tzdata \
    texinfo bison \
    binutils gcc g++ zlib-dev gettext-dev linux-headers \
    file flex gawk libtool perl coreutils curl-dev libidn2 libssl3 libcrypto3

RUN adduser --disabled-password --gecos '' ${USER_NAME} \
    && echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers

USER ${USER_NAME}

RUN mkdir -p /home/${USER_NAME}/prerequisities
WORKDIR /home/${USER_NAME}/prerequisities

ARG GCC_VERSION

RUN curl -LO https://gcc.gnu.org/pub/gcc/releases/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.xz \
&& tar -xf gcc-${GCC_VERSION}.tar.xz \
&& rm gcc-${GCC_VERSION}.tar.xz


RUN cd gcc-${GCC_VERSION} \
&& ./contrib/download_prerequisites \
&& CFG_OPTIONS="--enable-languages=c,c++ --enable-shared --enable-linker-build-id --with-system-zlib --without-included-gettext --enable-threads=posix --enable-nls --enable-clocale=generic --enable-libstdcxx-debug --enable-libstdcxx-time=yes --disable-werror --enable-checking=release --with-pic --disable-symvers --enable-obsolete \
--disable-libstdcxx-visibility --with-tune=generic --enable-libstdcxx-debug-flags=-gdwarf-2 --disable-multilib --disable-libsanitizer \
--build=x86_64-linux-musl --host=x86_64-linux-musl --target=x86_64-linux-musl --disable-libstdcxx-backtrace"  \
&& echo $CFG_OPTIONS \
&& ./configure --prefix=/opt/gcc-${GCC_VERSION} $CFG_OPTIONS \
&& make -j2 \
&& sudo make install \
&& cd - \
&& rm -rf gcc-${GCC_VERSION}

ARG BINUTILS_VERSION

RUN curl -LO https://ftp.gnu.org/gnu/binutils/binutils-${BINUTILS_VERSION}.tar.xz \
&& tar -xf binutils-${BINUTILS_VERSION}.tar.xz \
&& rm binutils-${BINUTILS_VERSION}.tar.xz

RUN cd binutils-${BINUTILS_VERSION} \
&& ./configure --help \
&& ./configure --prefix=/opt/binutils-${BINUTILS_VERSION} --enable-gold  --build=x86_64-linux-musl --host=x86_64-linux-musl --target=x86_64-linux-musl --enable-shared --disable-multilib --with-system-zlib --enable-install-libiberty  --disable-gprofng --enable-ld=default --enable-64-bit-bfd --enable-relro --enable-deterministic-archives --enable-default-execstack=no --enable-default-hash-style=gnu --with-pic  --disable-werror --disable-nls --with-mmap \
&& make -j$(nproc) \
&& sudo make install \
&& cd - \
&& rm -rf binutils-${BINUTILS_VERSION}

ARG CMAKE_VERSION

RUN curl -LO https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz \
  && tar -xf cmake-${CMAKE_VERSION}.tar.gz \
  && rm cmake-${CMAKE_VERSION}.tar.gz

RUN cd cmake-${CMAKE_VERSION} \
 && ./bootstrap --prefix=/opt/cmake-${CMAKE_VERSION} --parallel="${nproc:-2}"\
 && make -j$(nproc)\
 && sudo make install

FROM alpine:${ALPINE_VERSION}

COPY --from=devtools_alpine /opt /opt

ARG USER_NAME=build

RUN apk add --no-cache sudo curl wget git make autoconf bzip2 \
    libstdc++ libintl icu musl-dev curl-dev libidn2 libssl3 libcrypto3 linux-headers \
    python3 py3-pip py3-virtualenv bash

RUN adduser --disabled-password --gecos '' ${USER_NAME} \
    && echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers

ARG BINUTILS_VERSION
ARG CMAKE_VERSION
ARG GCC_VERSION

RUN set -eux; \
    ln -sf "/opt/binutils-${BINUTILS_VERSION}" /opt/php-distro-build-binutils; \
    ln -sf "/opt/cmake-${CMAKE_VERSION}"       /opt/php-distro-build-cmake; \
    ln -sf "/opt/gcc-${GCC_VERSION}"               /opt/php-distro-build-gcc

USER ${USER_NAME}

ENV PATH="/opt/php-distro-build-binutils/bin:/opt/php-distro-build-cmake/bin:/opt/php-distro-build-gcc/bin:${PATH}"

ENV CMAKE_INSTALL_PREFIX=/opt/php-distro-build-cmake

RUN cmake --version \
    && ld --version | head -n 1 \
    &&  gcc --version | head -n 1
