---

name: build-php-code-for-packages

on:
  workflow_call: ~
  workflow_dispatch: ~

permissions:
  contents: read

jobs:
  build-php-code-for-packages:
    name: build-php-code-for-packages
    runs-on: ubuntu-latest
    timeout-minutes: 300
    strategy:
      fail-fast: false
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Build PHP code (production code and its dependencies) for the packages
        run: |
          source ./tools/read_properties.sh
          read_properties project.properties PROJECT_PROPERTIES
          PHP_VERSIONS=${PROJECT_PROPERTIES_SUPPORTED_PHP_VERSIONS//[()]/}
          ./tools/build/build_php_code_for_packages.sh --php_versions "${PHP_VERSIONS}"
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: php-code-for-packages
          path: |
            _BUILT/php_code_for_packages
            _BUILT/NOTICE
