---

name: test-otel-unit

on:
  workflow_call: ~

permissions:
  contents: read

env:
  BUILT_PACKAGES_DIR: _BUILT/packages
  OTEL_UNIT_RESULTS_DIR: _BUILT/otel_unit_results

jobs:
  generate-php-versions:
    uses: ./.github/workflows/generate-php-versions.yml

  test-otel-unit:
    name: test-otel-unit
    runs-on: 'ubuntu-latest'
    needs: generate-php-versions
    timeout-minutes: 300
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-php-versions.outputs.php-versions) }}
    env:
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Download package artifacts for Debian AMD64
        uses: actions/download-artifact@v7
        with:
          pattern: packages-linux-x86-64
          path: ${{ env.BUILT_PACKAGES_DIR }}

      - name: Run otel instrumentation unit tests
        continue-on-error: true
        run: |
          PACKAGE_FILE=$(find ${{ env.BUILT_PACKAGES_DIR }} -name opentelemetry-php-distro*amd64.deb)
          ./tools/build/test_otel_unit_tests_in_docker.sh --php_versions "${PHP_VERSION}" --results_path "${{ env.OTEL_UNIT_RESULTS_DIR }}" --deb_package ${PACKAGE_FILE}

      - name: Generate test summary
        if: always()
        run: ./tools/build/junit_summary.py --path-to-test-results "${{ env.OTEL_UNIT_RESULTS_DIR }}/**/*.xml" --header "Test summary for PHP ${PHP_VERSION}" >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v6
        if: always()
        continue-on-error: true
        with:
          name: test-otel-unit-${{ matrix.php-version }}
          path: |
            ${{ env.OTEL_UNIT_RESULTS_DIR }}/*
